config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :journalists

  root 'dashboard#index'

  get 'dashboard' => 'dashboard#index'

  get 'analysis' => 'dashboard#doc_collection_analysis'
end

app/models/journalist.rb
class Journalist < ApplicationRecord
  has_many :articles

  validates :first, presence: true, length: { in: 1..100 }

end

app/controllers/journalists_controller.rb
class JournalistsController < ApplicationController
  before_action :set_journalist, only: [:show, :edit, :update, :destroy]

  # GET /journalists
  # GET /journalists.json
  def index
    @journalists = Journalist.all
  end

  # GET /journalists/1
  # GET /journalists/1.json
  def show
  end

  # GET /journalists/new
  def new
    @journalist = Journalist.new
  end

  # GET /journalists/1/edit
  def edit
  end

  # POST /journalists
  # POST /journalists.json
  def create
    @journalist = Journalist.new(journalist_params)

    respond_to do |format|
      if @journalist.save
        format.html { redirect_to @journalist, notice: 'Journalist was successfully created.' }
        format.json { render :show, status: :created, location: @journalist }
      else
        format.html { render :new }
        format.json { render json: @journalist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journalists/1
  # PATCH/PUT /journalists/1.json
  def update
    respond_to do |format|
      if @journalist.update(journalist_params)
        format.html { redirect_to @journalist, notice: 'Journalist was successfully updated.' }
        format.json { render :show, status: :ok, location: @journalist }
      else
        format.html { render :edit }
        format.json { render json: @journalist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journalists/1
  # DELETE /journalists/1.json
  def destroy
    @journalist.destroy
    respond_to do |format|
      format.html { redirect_to journalists_url, notice: 'Journalist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journalist
      @journalist = Journalist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journalist_params
      params.require(:journalist).permit(:first, :last)
    end
end

app/helpers/journalists_helper.rb
module JournalistsHelper
end

app/views/journalists/_form.html.erb
<%= form_with(model: journalist, local: true) do |form| %>
  <% if journalist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(journalist.errors.count, "error") %> prohibited this journalist from being saved:</h2>

      <ul>
      <% journalist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first %>
    <%= form.text_field :first %>
  </div>

  <div class="field">
    <%= form.label :last %>
    <%= form.text_field :last %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/journalists/edit.html.erb
<h1>Editing Journalist</h1>

<%= render 'form', journalist: @journalist %>

<%= link_to 'Show', @journalist %> |
<%= link_to 'Back', journalists_path %>

app/views/journalists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Journalists</h1>

<table>
  <thead>
    <tr>
      <th>First</th>
      <th>Last</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @journalists.each do |journalist| %>
      <tr>
        <td><%= journalist.first %></td>
        <td><%= journalist.last %></td>
        <td><%= link_to 'Show', journalist %></td>
        <td><%= link_to 'Edit', edit_journalist_path(journalist) %></td>
        <td><%= link_to 'Destroy', journalist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Journalist', new_journalist_path %>

app/views/journalists/new.html.erb
<h1>New Journalist</h1>

<%= render 'form', journalist: @journalist %>

<%= link_to 'Back', journalists_path %>

app/views/journalists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= "#{@journalist.first} #{@journalist.last}"%>

  <strong style="padding-left: 10em;">Count:</strong>
  <%= "#{@journalist.articles.length}" %>
</p>

<% @journalist.articles.each do |article| %>

  <p>
    <%= "#{article.created_at.strftime("%Y-%m-%d")}:"; %>
    <%= link_to(article.link, article.link, method: :get) %>
  </p>
<% end %>

<%= link_to 'Edit', edit_journalist_path(@journalist) %> |
<%= link_to 'Back', journalists_path %>